export type TaskStatus = "suggestions" | "ready" | "in-progress" | "review" | "completed";
export type Priority = "low" | "medium" | "high" | "urgent";
export type Assignee = "danny" | "hermes" | "both";

export interface Task {
  id: string;
  title: string;
  description: string;
  status: TaskStatus;
  priority: Priority;
  assignee: Assignee;
  tags: string[];
  createdAt: string;
  updatedAt: string;
  project: string;
}

export interface Column {
  id: TaskStatus;
  label: string;
  color: string;
}

export const COLUMNS: Column[] = [
  { id: "suggestions", label: "Suggestions", color: "#f59e0b" },
  { id: "ready", label: "Ready", color: "#3b82f6" },
  { id: "in-progress", label: "In Progress", color: "#8b5cf6" },
  { id: "review", label: "Review", color: "#ef4444" },
  { id: "completed", label: "Completed", color: "#22c55e" },
];

export interface Project {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
}

export const PROJECTS: Project[] = [
  { id: "daniel-search", name: "daniel-search", description: "Personal portfolio search experience", icon: "🔍", color: "#3b82f6" },
  { id: "ai-label", name: "ai-label", description: "AI-powered record label platform", icon: "🎵", color: "#8b5cf6" },
  { id: "openclaw", name: "openclaw", description: "Multi-agent AI gateway system", icon: "🤖", color: "#ef4444" },
  { id: "research-hub", name: "research-hub", description: "Interactive research canvas", icon: "📊", color: "#22c55e" },
  { id: "general", name: "general", description: "Cross-project tasks and ideas", icon: "⚡", color: "#f59e0b" },
];

export const INITIAL_TASKS: Task[] = [
  // === DANIEL-SEARCH ===
  {
    id: "ds-1",
    title: "Add 'At a Glance' credibility bar",
    description: "Horizontal micro-stats row below hero: years coding, projects shipped, current role, focus area. Pill/badge style.",
    status: "suggestions",
    priority: "high",
    assignee: "hermes",
    tags: ["social-proof", "homepage"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-2",
    title: "Add external links to project cards",
    description: "Render href (live demo) and repo (GitHub) links on ItemCard. Arrow + GitHub icons. Hover: muted → foreground.",
    status: "suggestions",
    priority: "high",
    assignee: "hermes",
    tags: ["social-proof", "projects"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-3",
    title: "Add 'Currently At' Amazon badge",
    description: "Small pill near hero: 'Currently: GM Assistant @ Amazon · Miami, FL'. Briefcase icon optional.",
    status: "suggestions",
    priority: "high",
    assignee: "hermes",
    tags: ["social-proof", "homepage"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-4",
    title: "Add 'Built with' tech logo strip",
    description: "Horizontal strip: Next.js, TypeScript, Tailwind, Vercel, Local LLMs. Grayscale, muted opacity, hover full.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["social-proof", "homepage"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-5",
    title: "Add quantifiable metrics to descriptions",
    description: "Update data.ts with numbers: '500+ daily interactions', '$X/month processed', '95+ Lighthouse'.",
    status: "suggestions",
    priority: "medium",
    assignee: "danny",
    tags: ["social-proof", "copy"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-6",
    title: "Add testimonial / endorsement section",
    description: "Blockquote with third-party quote. Left border foreground, italic muted. Even one quote beats zero.",
    status: "suggestions",
    priority: "low",
    assignee: "danny",
    tags: ["social-proof", "testimonials"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  // === AI-LABEL ===
  {
    id: "al-1",
    title: "Set up Supabase schema for artists",
    description: "Tables: artists, tracks, releases, distributions. RLS policies.",
    status: "ready",
    priority: "high",
    assignee: "hermes",
    tags: ["backend", "database"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "ai-label",
  },
  {
    id: "al-2",
    title: "Build track upload flow",
    description: "Drag-and-drop upload to R2, metadata extraction, waveform preview.",
    status: "in-progress",
    priority: "high",
    assignee: "hermes",
    tags: ["frontend", "upload"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "ai-label",
  },
  {
    id: "al-3",
    title: "Design artist dashboard UI",
    description: "Analytics, release management, earnings overview. Mobile-first.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["design", "dashboard"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "ai-label",
  },
  // === OPENCLAW ===
  {
    id: "oc-1",
    title: "Document multi-agent routing",
    description: "Clear docs on how main + stacy agents route messages and share context.",
    status: "ready",
    priority: "medium",
    assignee: "hermes",
    tags: ["docs", "routing"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "openclaw",
  },
  {
    id: "oc-2",
    title: "Add agent memory persistence",
    description: "SQLite-backed memory with context window management and retrieval.",
    status: "suggestions",
    priority: "high",
    assignee: "hermes",
    tags: ["backend", "memory"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "openclaw",
  },
  // === RESEARCH-HUB ===
  {
    id: "rh-1",
    title: "Add full-text search",
    description: "Integrate Fuse.js or similar for fuzzy search across all research notes.",
    status: "in-progress",
    priority: "medium",
    assignee: "hermes",
    tags: ["search", "frontend"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "research-hub",
  },
  {
    id: "rh-2",
    title: "Export notes to PDF",
    description: "Generate styled PDFs from markdown research notes with citations.",
    status: "suggestions",
    priority: "low",
    assignee: "hermes",
    tags: ["export", "pdf"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "research-hub",
  },
  // === GENERAL ===
  {
    id: "gn-1",
    title: "Kanban drag-and-drop",
    description: "Native HTML5 DnD or @dnd-kit for moving tasks between columns.",
    status: "in-progress",
    priority: "high",
    assignee: "hermes",
    tags: ["kanban", "ux"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "general",
  },
  {
    id: "gn-2",
    title: "Kanban localStorage persistence",
    description: "Persist task state to localStorage. Export/import JSON backup.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["kanban", "data"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "general",
  },
  {
    id: "gn-3",
    title: "Fix: Wire up task creation modal",
    description: "CRITICAL BUG: Modal form has no useState, inputs uncontrolled, 'Create Task' button only closes modal. Wire controlled inputs + createTask handler.",
    status: "ready",
    priority: "urgent",
    assignee: "hermes",
    tags: ["bug", "kanban", "critical"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "general",
  },
  {
    id: "gn-4",
    title: "Fix: Register column drop zones with useDroppable",
    description: "CRITICAL BUG: Columns don't use useDroppable — dropping onto empty columns silently fails. Add useDroppable to column wrappers.",
    status: "ready",
    priority: "urgent",
    assignee: "hermes",
    tags: ["bug", "dnd", "critical"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "general",
  },
  {
    id: "gn-5",
    title: "Fix: Add onDragOver for optimistic column updates",
    description: "BUG: No onDragOver handler — cards snap jarrily after drop only. Add optimistic column preview during drag.",
    status: "ready",
    priority: "high",
    assignee: "hermes",
    tags: ["bug", "dnd", "ux"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "general",
  },
  {
    id: "gn-6",
    title: "Fix: Replace console.log with task detail drawer",
    description: "BUG: Desktop task click does console.log — no detail view. Replace with slide-in drawer (desktop) / bottom sheet (mobile).",
    status: "ready",
    priority: "high",
    assignee: "hermes",
    tags: ["bug", "ux", "feature"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "general",
  },
  {
    id: "gn-7",
    title: "Fix: Mobile backdrop AnimatePresence",
    description: "BUG: Mobile bottom sheet backdrop pops off instantly instead of fading. Wrap in AnimatePresence.",
    status: "ready",
    priority: "medium",
    assignee: "hermes",
    tags: ["bug", "mobile", "animation"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "general",
  },
  {
    id: "gn-8",
    title: "Add accessibility: aria-labels, focus trapping, SR announcements",
    description: "Icon-only buttons lack aria-label. Form labels not linked. Modal doesn't trap focus. No SR announcement on DnD. Priority dots color-only.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["a11y", "ux"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "general",
  },
  {
    id: "gn-9",
    title: "Refactor: Split monolithic page.tsx into components",
    description: "page.tsx is 582 lines with SortableTask, KanbanColumn, MobileColumnView, DnD logic. Extract to separate files. Remove duplicated sidebar markup.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["refactor", "architecture"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "general",
  },
  {
    id: "gn-10",
    title: "Add localStorage persistence",
    description: "State resets on refresh. Hydrate from localStorage on mount, sync on change. Add loading state to avoid hydration flicker.",
    status: "suggestions",
    priority: "high",
    assignee: "hermes",
    tags: ["feature", "data", "persistence"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "general",
  },
  {
    id: "gn-11",
    title: "Add due dates + overdue highlighting",
    description: "Add optional dueDate to Task type. Render as date chip. Color red when past due. High signal, low effort.",
    status: "suggestions",
    priority: "low",
    assignee: "hermes",
    tags: ["feature", "ux"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "general",
  },
  {
    id: "gn-12",
    title: "Add search / filter bar",
    description: "Search input in header + assignee filter chips (D/H/B). Filter projectTasks before tasksByColumn. Essential at 20+ tasks.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["feature", "ux", "search"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "general",
  },
  {
    id: "gn-13",
    title: "Performance: React.memo + optimize handleDragEnd deps",
    description: "No React.memo on cards/columns — every drag re-renders all. handleDragEnd depends on tasks, recreating callback on every state change.",
    status: "suggestions",
    priority: "low",
    assignee: "hermes",
    tags: ["perf", "optimization"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "general",
  },
  // === DANIEL-SEARCH CRITICAL BUGS (from Opus review) ===
  {
    id: "ds-c1",
    title: "Fix broken nav links — 404s for half the nav",
    description: "CRITICAL: Nav.tsx links to /apps, /research, /code — none exist. Homepage category pills also route to dead pages. Every visitor hits 404. Either create routes or remove links.",
    status: "ready",
    priority: "urgent",
    assignee: "hermes",
    tags: ["bug", "nav", "critical", "404"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-c2",
    title: "Fix invalid Tailwind class pb-env(safe-area-inset-bottom)",
    description: "layout.tsx uses pb-env(...) which is not valid Tailwind v4. Use pb-[env(safe-area-inset-bottom)] arbitrary value instead.",
    status: "ready",
    priority: "high",
    assignee: "hermes",
    tags: ["bug", "css", "tailwind"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-c3",
    title: "Fix theme-color metadata API",
    description: "theme-color set via metadata.other is wrong API. Use export viewport with themeColor array for light/dark variants.",
    status: "ready",
    priority: "high",
    assignee: "hermes",
    tags: ["bug", "metadata", "seo"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-c4",
    title: "Verify /api/ask endpoint exists or add graceful fallback",
    description: "ask/page.tsx POSTs to /api/ask but no route found. Page silently errors. Either create the API route or show 'Coming soon' UI instead of fake-loading.",
    status: "ready",
    priority: "high",
    assignee: "hermes",
    tags: ["bug", "api", "ask"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-c5",
    title: "Fix searchItems running twice per render",
    description: "search/page.tsx calls searchItems(q).length AND SearchResults child calls searchItems(q) again. Pass results down or useMemo.",
    status: "ready",
    priority: "medium",
    assignee: "hermes",
    tags: ["bug", "perf", "search"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-c6",
    title: "Fix Suspense boundary that never shows fallback",
    description: "SearchResults is async but searchItems is sync — Suspense never triggers. Use loading.tsx or actually defer work.",
    status: "ready",
    priority: "medium",
    assignee: "hermes",
    tags: ["bug", "suspense", "react"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  // === DANIEL-SEARCH A11Y ===
  {
    id: "ds-a1",
    title: "Add aria-labels to icon-only buttons",
    description: "Hamburger, close, and 'New Task' icon-only buttons have no aria-label. Screen readers can't identify them.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["a11y", "nav"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-a2",
    title: "Link form labels to inputs via htmlFor",
    description: "Modal form labels are not linked to inputs. Add htmlFor/id pairs for accessibility.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["a11y", "forms"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-a3",
    title: "Add focus trap to modal",
    description: "Modal does not trap focus — Tab escapes into background content. Implement focus trap for keyboard users.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["a11y", "modal"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-a4",
    title: "Add non-color priority indicators",
    description: "Priority communicated by color dot only. Add text label or aria-label for screen readers.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["a11y", "cards"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-a5",
    title: "Remove autoFocus from homepage search",
    description: "autoFocus on landing page steals focus from screen reader landmark navigation (WCAG 2.4.3). Remove or keep only on /search.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["a11y", "homepage"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-a6",
    title: "Fix heading hierarchy on homepage",
    description: "Homepage has h1 then jumps to no h2 for 'Featured' section. Add h2 (visually hidden if needed) for proper outline.",
    status: "suggestions",
    priority: "low",
    assignee: "hermes",
    tags: ["a11y", "headings"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  // === DANIEL-SEARCH PERFORMANCE ===
  {
    id: "ds-p1",
    title: "Add viewport export",
    description: "No mobile viewport meta declared. Add export viewport with width=device-width, initial-scale=1.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["perf", "mobile", "seo"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-p2",
    title: "Replace img with next/image in Nav",
    description: "Nav uses raw img without width/height. Use next/image for LCP and Lighthouse score improvement.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["perf", "lcp", "images"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-p3",
    title: "Pause search glow animation when off-screen",
    description: "Infinite conic-gradient animation on search bar runs on every page. Use IntersectionObserver to pause when off-screen or not focused.",
    status: "suggestions",
    priority: "low",
    assignee: "hermes",
    tags: ["perf", "animation"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-p4",
    title: "Optimize searchItems and category filtering",
    description: "searchItems is O(n*m) string concat. categories iterates whole items per category. Pre-index or use Object.groupBy.",
    status: "suggestions",
    priority: "low",
    assignee: "hermes",
    tags: ["perf", "search"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  // === DANIEL-SEARCH SOCIAL PROOF FEATURES ===
  {
    id: "ds-f1",
    title: "Add real href/repo links to all project items",
    description: "Every Item.href is undefined. Portfolio without GitHub/live-demo links reads as vapor. Add repo and href to every item, render both in cards.",
    status: "suggestions",
    priority: "high",
    assignee: "hermes",
    tags: ["social-proof", "links", "critical"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-f2",
    title: "Add GitHub embed with star counts and languages",
    description: "Surface live GitHub data on homepage: star counts, language chips, last-commit recency. Live data > static descriptions.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["social-proof", "github", "api"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-f3",
    title: "Create case study pages /projects/[id]",
    description: "Each project should have a dedicated page with screenshots, problem/approach/result narrative, tech stack, and links. Currently gallery is just paragraphs.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["social-proof", "case-study", "pages"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-f4",
    title: "Add OG images and opengraph-image.tsx",
    description: "Sharing URL on LinkedIn produces blank card. Add opengraph-image.tsx for rich social previews.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["social-proof", "seo", "og"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-f5",
    title: "Add robots.txt and sitemap.xml",
    description: "Next.js makes both one-liners. Essential for SEO and crawler indexing.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["seo", "sitemap"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-f6",
    title: "Add analytics (Vercel or Plausible)",
    description: "Track which projects get traffic. Signals site is maintained. Recruiters care about active portfolios.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["analytics", "tracking"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-f7",
    title: "Add contact CTA above the fold",
    description: "Email buried in /about and /resume. Add small footer/header CTA: email + GitHub + LinkedIn visible on every page.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["social-proof", "contact", "cta"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-f8",
    title: "Add 'Currently building' activity signal",
    description: "Line under hero showing most recent commit or pinned note. Signals site is alive and actively maintained.",
    status: "suggestions",
    priority: "low",
    assignee: "hermes",
    tags: ["social-proof", "activity"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-f9",
    title: "Add testimonials / press / talks section",
    description: "Even one quote lifts credibility disproportionately. Add blockquote section with left border.",
    status: "suggestions",
    priority: "low",
    assignee: "danny",
    tags: ["social-proof", "testimonials"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-f10",
    title: "Add /ask graceful degradation + example output",
    description: "When API breaks, show precomputed example exchange. Currently shows 'Something went wrong' with no context.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["ux", "ask", "fallback"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-f11",
    title: "Add resume PDF download button",
    description: "Recruiters paste resumes into ATS. Make it trivial with a 'Download PDF' button next to resume title.",
    status: "suggestions",
    priority: "low",
    assignee: "hermes",
    tags: ["social-proof", "resume", "pdf"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-f12",
    title: "Add JSON-LD Person schema",
    description: "Free SEO wins for 'Daniel Silva Perez'. Add structured data in layout.tsx.",
    status: "suggestions",
    priority: "low",
    assignee: "hermes",
    tags: ["seo", "schema", "json-ld"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  // === DANIEL-SEARCH UX ===
  {
    id: "ds-u1",
    title: "Add ⌘K / '/' keyboard shortcut for search",
    description: "Portfolio with search bar should support keyboard shortcut. The ↵ kbd hint teases affordance not delivered.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["ux", "keyboard", "search"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-u2",
    title: "Add live autosuggest as you type",
    description: "Search has no autosuggest. With 9 items it's instant to filter live with highlighted matches.",
    status: "suggestions",
    priority: "medium",
    assignee: "hermes",
    tags: ["ux", "search", "autosuggest"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-u3",
    title: "Add custom not-found.tsx page",
    description: "Given broken nav links, a custom 404 with search bar and links home is essential. Currently falls back to generic Next.js 404.",
    status: "suggestions",
    priority: "high",
    assignee: "hermes",
    tags: ["ux", "404", "error"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-u4",
    title: "Add manual theme toggle",
    description: "Dark mode only via OS preference. Many users want manual toggle (recruiters on managed laptops locked to light).",
    status: "suggestions",
    priority: "low",
    assignee: "hermes",
    tags: ["ux", "theme", "dark-mode"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-u5",
    title: "Enhance footer with social links + 'Built with'",
    description: "Footer is single line. Add GitHub, Email, LinkedIn, 'Built with Next.js', source code link to this repo.",
    status: "suggestions",
    priority: "low",
    assignee: "hermes",
    tags: ["ux", "footer", "social"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-u6",
    title: "Show hover arrows always on mobile",
    description: "Hover-only 'open in new tab' arrow invisible on touch. Show always on mobile or use persistent icon.",
    status: "suggestions",
    priority: "low",
    assignee: "hermes",
    tags: ["ux", "mobile", "touch"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
  {
    id: "ds-u7",
    title: "Increase mobile tap targets to 44px",
    description: "Mobile nav tap targets are ~40px. WCAG recommends 44px minimum. Bump py-2.5 to py-3.",
    status: "suggestions",
    priority: "low",
    assignee: "hermes",
    tags: ["ux", "mobile", "a11y"],
    createdAt: "2026-05-02",
    updatedAt: "2026-05-02",
    project: "daniel-search",
  },
];
